### ISSUE TITLE
Nested object method error

### ISSUE THREAD

**Issue by pisyell** [rosell-dk/js-expression#9]
```
const localContext = {
  "a": {
    'aaa': () => console.log(111111)
  }
}
const a = new JsExpression('a.aaa()');
a.setLocalContext(localContext);
const result1 = a.evaluate(); 

const b = new JsExpression('typeof a.aaa');
b.setLocalContext(localContext);
const result2 = b.evaluate(); 

console.log(result1);
// Uncaught Error: Function does not exist: aaa

console.log(result2);
// function
```

why?

**Comment by rosell-dk** [comment]
The library by design only allows executing functions provided in the context object (security concerns). Because it was the simplest thing to implement, it is also required that the function is a direct "child" to the context object. The implementation is in principle like this: `return localContext[nameOfFunction]()` (The real implementation is here: https://github.com/rosell-dk/js-expression/blob/master/src/Evaluator.js#L165-L183).

I can see that it is more restrictive than what is required to make it secure. The current implementation is simply a very simple way to implement a safe function evaluation, which rejects things like `window.eval()`
